
import { useRouter } from "next/router";
import Cookies from "js-cookie";
import Head from 'next/head';
import * as React from 'react';
import { Iconly } from 'react-iconly';
import { 
  NextUIProvider,
  Button,
  Input,
  Spacer,
  Link,
  Card,
  Grid,
  useTheme, Text,Row

} from '@nextui-org/react';

const Login = () => {
    const colors = [
        'primary',
        'secondary',
        'success',
        'warning',
        'error',
        'gradient'
        
      ];
    const router = useRouter();

    //ログイン処理（CookieにsignedIn=trueとする）
    const login = () => {
        Cookies.set("signedIn", "true");
        router.replace("/private");
    }

    return (
        <NextUIProvider>
        <Head>
        <title>Online Libraly</title>
        <meta
          name="description"
          content="Generated by create next app and using NextUI as a react UI library"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <spacer y={1}/>
      <Grid.Container gap={2} justify="center">
          
            <Grid xs={4} >
              <Card width="50%">
              <Card.Header justify="flex-start">
                  <Row justify="center">
                    
                    <Text weight={500} style={{ opacity: 0.6 }}>
                      <h3>こんにちは!!　(*^^*)</h3>
                    </Text>
                  </Row>        
              </Card.Header>
                <Card.Body css={{ p: 0 }}>
                  <Card.Image
                    objectFit="cover"
                    src="login_400x400.png"
                    width='50%'
                    height="auto"
                  />
                </Card.Body>
                
                <Grid width="100%">
                <Input label="パスワード" type="text" fullWidth/>
                <Spacer x={0.3}/>
                
                <Spacer y={1}/>
                
                 <Button auto color="warning" css={{ px: '$13' }} rounded fullWidth
                 iconRight={<Iconly name="Send" set="bulk" primaryColor="Darkgreen"/>} onClick={login}>
                  
                  <Link href="/"><a>教材棚へGO!!!　</a></Link>
                  </Button>
                
                  </Grid>
                
              <Spacer y={1} />
              </Card>
            </Grid>
          
        </Grid.Container>
    </NextUIProvider>
    );
}

export default Login;